---
description: "詳細情報: '<labelname>' は、このステートメントを含まない 'Try'、'Catch'、または 'Finally' ステートメントの内側にあるため、'GoTo <labelname>' は有効ではありません"
title: "'<labelname>' は、このステートメントを含まない 'Try'、'Catch' または 'Finally' ステートメントの内側にあるため、'GoTo <labelname>' は有効ではありません。"
ms.date: 07/20/2015
f1_keywords:
- bc30754
- vbc30754
helpviewer_keywords:
- BC30754
ms.assetid: 2eefc7fb-fdf0-41e9-bf60-c3bc93580e14
ms.openlocfilehash: 952612fbac2304f57cf2d0a7ac6e701f1d5bb054
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/14/2021
ms.locfileid: "100437411"
---
# <a name="goto-labelname-is-not-valid-because-labelname-is-inside-a-try-catch-or-finally-statement-that-does-not-contain-this-statement"></a>'\<labelname>' は、このステートメントを含まない 'Try'、'Catch' または 'Finally' ステートメントの内側にあるため、'GoTo \<labelname>' は有効ではありません。

`Try...Catch...Finally` ブロック内に分岐することはできません。  
  
 **エラー ID:** BC30754  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- `Try...Catch...Finally` ブロックの前にラベルが配置されるように、コードを再構成します。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
