---
description: "詳細情報: ' On Error ' ステートメントは、' Using ' ステートメント内では有効ではありません"
title: "'On Error' ステートメントは、'Using' ステートメント内では使用できません"
ms.date: 07/20/2015
f1_keywords:
- vbc36013
- bc36013
helpviewer_keywords:
- BC36013
ms.assetid: 5b399bf9-6595-46e0-a808-378f6c28568b
ms.openlocfilehash: 49c3d55d5ef4eb7137144e60ee7ff02f4b119f3c
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/14/2021
ms.locfileid: "100456524"
---
# <a name="on-error-statements-are-not-valid-within-using-statements"></a>'On Error' ステートメントは、'Using' ステートメント内では使用できません

`On Error` ステートメントが `Using` ステートメント内で使用されていますが、このコンテキストには使用できません。  
  
 **エラー ID:** BC36013  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- `Try…Catch` ブロックなどの構造化エラー処理を `On Error` ステートメントの代わりに使用します。  
  
## <a name="see-also"></a>関連項目

- [On Error ステートメント](../language-reference/statements/on-error-statement.md)
- [Try ブロックと Catch ブロックを使用して例外をキャッチする方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
