---
title: "'<name1>' は '<name2>' から継承するため、'Catch' ブロックは到達しませんでした"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: fe716108281b3df64c3d444c54bee8dea3fcb82f
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/28/2019
ms.locfileid: "64755853"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>'\<name1>' は '\<name2>' から継承するため、'Catch' ブロックは到達しませんでした
コード内の `Catch` ブロックに到達することはありません。  
  
 既定では、このメッセージは警告です。 警告を非表示にする方法や、警告をエラーとして扱う方法の詳細については、「[Visual Basic での警告の構成](/visualstudio/ide/configuring-warnings-in-visual-basic)」を参照してください。  
  
 **エラー ID:** BC42029  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- 余分な `Catch` ブロックを削除します。  
  
## <a name="see-also"></a>関連項目

- [例外をキャッチする try/catch ブロックを使用する方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally ステートメント](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
