---
description: "詳細: '<name1>' は '<name2>' から継承するため、'Catch' ブロックに到達することはありません"
title: "'<name1>' は '<name2>' から継承するため、'Catch' ブロックに到達することはありません"
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 9fbbad2d11f261f68ad1e4f63cb691805d59995e
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 02/14/2021
ms.locfileid: "100422758"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>'\<name1>' は '\<name2>' から継承するため、'Catch' ブロックに到達することはありません

コード内の `Catch` ブロックに到達することはありません。  
  
 既定では、このメッセージは警告です。 警告を非表示にする方法や、警告をエラーとして扱う方法の詳細については、「 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)」を参照してください。  
  
 **エラー ID:** BC42029  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- 余分な `Catch` ブロックを削除します。  
  
## <a name="see-also"></a>関連項目

- [Try ブロックと Catch ブロックを使用して例外をキャッチする方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
